Car.create(name: "Emily's Corsa")

  # FullFill.create(car_id: 1, complete: true)
  #   PartialFill.create(full_fill_id: 1, price_per_litre: 129.9, total_price: 25.02, miles_complete: 184, fully_filled: true)
  # FullFill.create(car_id: 1, complete: true)
  #   PartialFill.create(full_fill_id: 2, price_per_litre: 131.9, total_price: 30.00, miles_complete: 310, fully_filled: false)
  #   PartialFill.create(full_fill_id: 2, price_per_litre: 131.8, total_price: 45.65, miles_complete: 281, fully_filled: true)
  # FullFill.create(car_id: 1, complete: true)
  #   PartialFill.create(full_fill_id: 3, price_per_litre: 130.9, total_price: 51.19, miles_complete: 371, fully_filled: true)
  # FullFill.create(car_id: 1, complete: true)
  #   PartialFill.create(full_fill_id: 4, price_per_litre: 132.9, total_price: 20.01, miles_complete: 256, fully_filled: false)
  #   PartialFill.create(full_fill_id: 4, price_per_litre: 132.9, total_price: 30.00, miles_complete: 211, fully_filled: false)
  #   PartialFill.create(full_fill_id: 4, price_per_litre: 131.9, total_price: 42.89, miles_complete: 264, fully_filled: true)
  # FullFill.create(car_id: 1, complete: false)
  #   PartialFill.create(full_fill_id: 5, price_per_litre: 130.9, total_price: 50.48, miles_complete: 384, fully_filled: false)


Car.create(name: "Marc's BMW")
  
  # FullFill.create(car_id: 2, complete: true)
  #   PartialFill.create(full_fill_id: 6, price_per_litre: 131.9, total_price: 78.18, miles_complete: 606.4, fully_filled: true)
  # FullFill.create(car_id: 2, complete: true)
  #   PartialFill.create(full_fill_id: 7, price_per_litre: 132.9, total_price: 75.45, miles_complete: 616.2, fully_filled: true)
  # FullFill.create(car_id: 2, complete: true)
  #   PartialFill.create(full_fill_id: 8, price_per_litre: 131.9, total_price: 40.02, miles_complete: 594.1, fully_filled: false)
  #   PartialFill.create(full_fill_id: 8, price_per_litre: 133.9, total_price: 68.15, miles_complete: 326.9, fully_filled: true)
  # FullFill.create(car_id: 2, complete: true)
  #   PartialFill.create(full_fill_id: 9, price_per_litre: 130.9, total_price: 72.02, miles_complete: 600.2, fully_filled: true)
  # FullFill.create(car_id: 2, complete: true)
  #   PartialFill.create(full_fill_id: 10, price_per_litre: 131.9, total_price: 78.88, miles_complete: 614.1, fully_filled: true)

Car.create(name: "Lynda's Toyota")

  # FullFill.create(car_id: 3, complete: true)
  #   PartialFill.create(full_fill_id: 11, price_per_litre: 129.9, total_price: 45.74, miles_complete: 410, fully_filled: true)
  # FullFill.create(car_id: 3, complete: true)
  #   PartialFill.create(full_fill_id: 12, price_per_litre: 129.9, total_price: 41.16, miles_complete: 380, fully_filled: true)
  # FullFill.create(car_id: 3, complete: true)
  #   PartialFill.create(full_fill_id: 13, price_per_litre: 128.9, total_price: 40.27, miles_complete: 391, fully_filled: true)
  # FullFill.create(car_id: 3, complete: true)
  #   PartialFill.create(full_fill_id: 14, price_per_litre: 129.9, total_price: 38.95, miles_complete: 394, fully_filled: true)
  # FullFill.create(car_id: 3, complete: true)
  #   PartialFill.create(full_fill_id: 15, price_per_litre: 130.9, total_price: 20.00, miles_complete: 302, fully_filled: false)
  #   PartialFill.create(full_fill_id: 15, price_per_litre: 129.9, total_price: 39.65, miles_complete: 297, fully_filled: true)
